version: '3.8'

services:
  front:
    container_name: kirinyaga-front
    build: ./front
    ports:
      - "${FRONT_PORT}:3000"
      - "24678:24678"
    volumes:
      - ./front:/app
    depends_on:
      - api
    env_file:
      - ./.env
  
  api:
    container_name: kirinyaga-api
    build:
      context: './api'
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./api:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./api/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    ports:
      - "8090:80"
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      ./api/.env
    depends_on:
      - mysql

volumes:
  db_data:
    driver: local